import type tag from "tagged-tag";
import type { GetTagMetadata, Tagged } from "type-fest";

export type { JsonOf } from "type-party";
export { jsonParse, jsonStringify, jsonStringifyUnstable } from "type-party/runtime/json.js";

export { type tag };

/**
 * This function accepts any JS string and encodes it in base64, using a UTF8
 * representation of the string to derive the underlying binary data.
 */
export function b64Encode<T extends string>(it: T) {
  return Buffer.from(it, "utf-8").toString("base64") as B64Of<T>;
}

/**
 * Base64 encodes arbitrary binary data in an array buffer.
 */
export function b64EncodeArrayBuffer<T extends ArrayBuffer>(it: T) {
  return Buffer.from(it).toString("base64") as unknown as B64Of<T>;
}

/**
 * This function accepts any b64 encoded string, as generated by
 *  {@link b64Encode}, and returns the original JS string that was encoded.
 */
export function b64Decode<T extends B64Of<string>>(it: T) {
  return Buffer.from(it, "base64").toString("utf-8") as GetTagMetadata<T, "B64">;
}

export function b64UrlEncode<T extends string>(it: T) {
  return b64ToB64Url(b64Encode(it));
}

export function b64UrlDecode<T extends B64UrlOf<string>>(it: T) {
  const b64String = b64UrlToB64(it);
  return b64Decode(b64String);
}

export function b64UrlToB64<T extends B64UrlOf<string>>(it: T) {
  return it.replaceAll("-", "+").replaceAll("_", "/") as B64Of<
    GetTagMetadata<T, "B64Url">
  >;
}

export function b64ToB64Url<T extends B64Of<string>>(it: T) {
  return it.replaceAll("+", "-").replaceAll("/", "_") as B64UrlOf<
    GetTagMetadata<T, "B64">
  >;
}

export type B64Of<T> = Tagged<string, "B64", T>;
export type B64UrlOf<T> = Tagged<string, "B64Url", T>;

/**
 * This function encodes a string in a way that allows it to be used as data in
 * an RFC 3986 URI. It extends the built-in `encodeURIComponent` to also percent
 * encode some extra characters that were only reserved (in certain contexts)
 * starting in RFC 3986. This encodes everything except A–Z a–z 0–9 - _ . ~,
 * which is the "unreserved" set in RFC 3986.
 */
export function encodeURIComponentRFC3986(
  str: `${string}${AlphaNumeric}`
): `${string}${AlphaNumeric}`;
export function encodeURIComponentRFC3986(str: string): string;
export function encodeURIComponentRFC3986(str: string) {
  return encodeURIComponent(str).replace(
    /[!'()*]/g,
    (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`
  );
}

export type UppercaseAlpha =
  | "A"
  | "B"
  | "C"
  | "D"
  | "E"
  | "F"
  | "G"
  | "H"
  | "I"
  | "J"
  | "K"
  | "L"
  | "M"
  | "N"
  | "O"
  | "P"
  | "Q"
  | "R"
  | "S"
  | "T"
  | "U"
  | "V"
  | "W"
  | "X"
  | "Y"
  | "Z";

export type Digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
export type AlphaNumeric = UppercaseAlpha | Lowercase<UppercaseAlpha> | Digit;
